language: java
install: true
jdk:
- openjdk14
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/modules-2/
  - $HOME/.gradle/wrapper/dists/
script:
- ./gradlew check
- ./gradlew jacocoTestReport
after_success:
- bash <(curl -s https://codecov.io/bash)
