version: "3"
services:
  zookeeper:
    image: zookeeper:3.5.8
    ports:
    - 2181
    environment:
    - JMXDISABLE=true
    - SERVER_JVMFLAGS=-Dzookeeper.jmx.log4j.disable=true
    - ZOO_DATA_DIR=/data
    - ZOO_DATA_LOG_DIR=/datalog
    - ZOO_ADMINSERVER_ENABLED=false
  kafka:
    image: neowu/kafka:2.6.0
    ports:
    - 9092:9092
    environment:
    - KAFKA_HEAP_OPTS=-Xms1G -Xmx1G
    - KAFKA_ARGS=--override advertised.listeners=PLAINTEXT://localhost:9092 --override num.partitions=3
    depends_on:
    - zookeeper
