version: "3"
services:
  zookeeper:
    image: zookeeper:3.5.7
    ports:
    - 2181
    environment:
    - JMXDISABLE=true
    - ZOO_DATA_DIR=/data
    - ZOO_DATA_LOG_DIR=/datalog
    - ZOO_ADMINSERVER_ENABLED=false
  kafka:
    image: neowu/kafka:2.5.0
    ports:
    - 9092:9092
    environment:
    - KAFKA_ARGS=--override advertised.listeners=PLAINTEXT://localhost:9092
    depends_on:
    - zookeeper
